language: python
python:
  - "3.13"

cache: pip

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls awsebcli

before_script:
  - python manage.py collectstatic --noinput
  - python manage.py migrate --noinput

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coveralls --service=travis-pro

jobs:
  include:
    - stage: deploy
      if: branch = main AND type = push
      script:
        - eb --version
        - eb status
        - cat .elasticbeanstalk/config.yml
        - eb deploy --staged
